{{- if and .Values.stork.enabled .Values.stork.server.enabled .Values.stork.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stork-server
  namespace: {{ .Values.global.namespace }}
  labels:
    app: stork-server
  {{- with .Values.stork.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.stork.ingress.className }}
  ingressClassName: {{ .Values.stork.ingress.className }}
  {{- end }}
  
  {{- if .Values.stork.ingress.tls.enabled }}
  tls:
  {{- range .Values.stork.ingress.hosts }}
  - hosts:
    - {{ . }}
    secretName: {{ . | replace "." "-" }}
  {{- end }}
  {{- end }}
  
  rules:
  {{- range .Values.stork.ingress.hosts }}
  - host: {{ . }}
    http:
      paths:
      - path: {{ $.Values.stork.ingress.path | default "/" }}
        pathType: {{ $.Values.stork.ingress.pathType | default "Prefix" }}
        backend:
          service:
            name: stork-server
            port:
              number: {{ $.Values.stork.server.port }}
  {{- end }}
{{- end }}
